SCREEN_WIDTH, SCREEN_HEIGHT = 720, 540
SCREEN_MARGIN = 10
WINDOW_WIDTH, WINDOW_HEIGHT = (SCREEN_WIDTH + SCREEN_MARGIN) + 256, (
    SCREEN_HEIGHT + SCREEN_MARGIN
) + 60
GAME_TITLE = "Particle Simulation"

# Screen coordinates
SCREENX_LEFT = SCREEN_MARGIN
SCREENX_RIGHT = SCREEN_WIDTH + SCREEN_MARGIN
SCREENY_TOP = SCREEN_MARGIN
SCREENY_BOTTOM = SCREEN_HEIGHT + SCREEN_MARGIN

PARTICLE_BT_SIZE = (50, 50)

BG_COLOR = (0, 0, 0)  # Black
BG_COLOR_2 = (32, 32, 32)
BASE_COLOR = (255, 255, 255)  # White

BUTTON_COLOR = (96, 96, 96)
BUTTON_HOVER = (64, 64, 64)

MAX_PARTICLES = 6000
